# Generated by Django 2.0 on 2020-01-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleColumn',
            new_name='DeviceSystem',
        ),
    ]
