# Generated by Django 2.0 on 2020-01-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManagement', '0003_auto_20200128_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='body',
        ),
    ]
